server:
  port: 8085
application:
    name: assessment
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assessment_db
    driver-class-name: org.postgresql.Driver
    username: assessment_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  freemarker:
    allow-session-override:

